const { contextBridge, ipcRenderer } = require('electron');
const invoke = (channel, payload) => ipcRenderer.invoke(channel, payload);
contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform, isElectron: true,
  getContext: () => invoke('app:get-context'), getOverviewStats: () => invoke('stats:overview'), pickVideo: () => invoke('video:pick'), useSampleVideo: () => invoke('video:use-sample'), compressVideo: (videoId) => invoke('video:compress', videoId), openCompressedVideoFolder: () => invoke('video:open-compressed-folder'), summarizeVideo: (videoId, method = 'audio', requestId) => invoke('video:summarize', { videoId, method, requestId }), analyzeVideo: (videoId) => invoke('video:analyze', videoId), generateSceneTranscripts: (videoId) => invoke('video:generate-transcripts', videoId), deleteVideo: (videoId) => invoke('video:delete', videoId),
  getSession: () => invoke('auth:session'), login: (payload) => invoke('auth:login', payload), logout: () => invoke('auth:logout'), getProfile: () => invoke('profile:get'), updateProfile: (payload) => invoke('profile:update', payload), pickProfileAvatar: () => invoke('profile:pick-avatar'), listPermissionUsers: () => invoke('permissions:list'), updateUserPermissions: (payload) => invoke('permissions:update', payload),
  getScenes: (videoId) => invoke('video:get-scenes', videoId), replaceKeyframe: (payload) => invoke('keyframe:replace', payload), listVideos: () => invoke('videos:list'), listClips: () => invoke('clips:list'), getClipDetail: (clipId) => invoke('clip:get-detail', clipId), listNotes: () => invoke('notes:list'), getDefaultNotebook: () => invoke('notes:get-default-notebook'), getNoteDetail: (noteId) => invoke('note:get-detail', noteId), deleteNote: (noteId) => invoke('note:delete', noteId), listTasks: () => invoke('tasks:list'),
  getModelConfig: () => invoke('config:model:get'), saveModelConfig: (payload) => invoke('config:model:save', payload),
  checkPermission: (payload) => invoke('permission:check', payload), getCreditSummary: () => invoke('credits:summary'), redeemCreditCode: (code) => invoke('credits:recharge', code), listCreditRechargeRecords: (query) => invoke('credits:recharge-records', query), listCreditConsumptionRecords: (query) => invoke('credits:consumption-records', query),
  listNoteTemplates: () => invoke('note-templates:list'), importNoteTemplate: () => invoke('note-templates:import'), exportNoteTemplate: (template) => invoke('note-templates:export', template),
  retryTask: (taskId, mode) => invoke('tasks:retry', { taskId, mode }), generateClip: (payload) => invoke('clip:generate', payload), generatePreviewClip: (payload) => invoke('clip:generate-preview', payload), deleteClip: (clipId) => invoke('clip:delete', clipId), mergeNotes: (payload) => invoke('notes:merge', payload), printTemplate: () => invoke('template:print'), openArtifact: (kind, id) => invoke('artifact:open', { kind, id }),
  onTaskUpdate: (callback) => { const listener = (_event, task) => callback(task); ipcRenderer.on('task:update', listener); return () => ipcRenderer.removeListener('task:update', listener); }
});
