import React, { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileText, ImagePlus, Merge } from "lucide-react";
import AppShell from "./components/AppShell";
import WorkbenchScreen from "./components/WorkbenchScreen";
import { Modal, ProcessingOverlay } from "./components/Shared";
import { clipRows, scenes } from "./data";
import { appApi, isElectron } from "./api";

const initialSelection = Object.fromEntries(scenes.map((scene) => [scene.id, scene.defaultSelected]));
const initialTranscripts = Object.fromEntries(scenes.map((scene) => [scene.id, scene.summary]));
const loadSelectionScreen = () => import("./components/SelectionScreen");
const SelectionScreen = lazy(loadSelectionScreen);
const TranscriptScreen = lazy(() => import("./components/TranscriptScreen"));
const TemplateScreen = lazy(() => import("./components/TemplateScreen"));
const LibraryScreen = lazy(() => import("./components/LibraryScreen"));
const NotesScreen = lazy(() => import("./components/NotesScreen"));

function CompletionModal({ onClose, onLibrary }) { return <Modal title="游学片段已生成" onClose={onClose}><div className="success-content"><span className="success-icon"><CheckCircle2 size={30} /></span><h3>游学片段.pdf</h3><p>场景与关键帧已整理为 PDF，可在游学片段中查看。</p><div className="file-summary"><FileText size={26} /><span><b>保存位置</b><small>本地素材库 / 输出文件</small></span></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>继续编辑</button><button className="primary-button" onClick={onLibrary}>查看游学片段</button></div></div></Modal>; }
function MergeModal({ selectedClips, clipData, onClose, onComplete }) { const rows = clipData.filter((clip) => selectedClips.includes(clip.id)); const [cover, setCover] = useState("default"); return <Modal title="合并为游学笔记" onClose={onClose} wide><div className="merge-content"><section><span className="inspector-label">已选片段 · 可拖动排序</span>{rows.map((row, index) => <div className="merge-row" key={row.id}><span>{index + 1}</span><FileText size={18} /><div><b>{row.name}</b><small>{row.pages || row.page_count || 0} 页</small></div><span>⠿</span></div>)}</section><section className="cover-choice"><span className="inspector-label">笔记封面</span><button className={cover === "default" ? "active" : ""} onClick={() => setCover("default")}><div className="cover-preview" /><span><b>使用首个片段封面</b><small>系统默认</small></span>{cover === "default" && <CheckCircle2 size={18} />}</button><button className={cover === "upload" ? "active" : ""} onClick={() => setCover("upload")}><span className="upload-cover"><ImagePlus size={22} /></span><span><b>上传自定义照片</b><small>JPG 或 PNG</small></span>{cover === "upload" && <CheckCircle2 size={18} />}</button></section></div><footer className="modal-footer"><div><b>{rows.reduce((sum, row) => sum + (row.pages || row.page_count || 0), 0)} 页</b><span>将生成 1 个新 PDF</span></div><button className="primary-button" onClick={() => onComplete(cover)}><Merge size={17} /> 开始合并</button></footer></Modal>; }

export default function App() {
  const [screen, setScreen] = useState("workbench"); const [selection, setSelection] = useState(initialSelection); const [activeScene, setActiveScene] = useState("scene-2"); const [view, setView] = useState("grid"); const [transcripts, setTranscripts] = useState(initialTranscripts); const [settings, setSettings] = useState({ template: "nature", accent: "green", showEducation: true, handwriting: true }); const [processing, setProcessing] = useState(""); const [completed, setCompleted] = useState(false); const [selectedClips, setSelectedClips] = useState([]); const [mergeOpen, setMergeOpen] = useState(false); const [videoId, setVideoId] = useState(null); const [sceneRows, setSceneRows] = useState(scenes); const [clipData, setClipData] = useState(clipRows); const [notes, setNotes] = useState([]); const [tasks, setTasks] = useState([]); const [taskCenterOpen, setTaskCenterOpen] = useState(false); const [notice, setNotice] = useState("");
  const projectName = useMemo(() => screen === "library" || screen === "notes" ? "2026 中小学研学素材库" : "上海植物园 · 自然观察研学", [screen]);
  const refresh = async () => { if (!isElectron) return; setClipData(await appApi.listClips()); setNotes(await appApi.listNotes()); setTasks(await appApi.listTasks()); };
  useEffect(() => { const onNotice = (event) => setNotice(String(event.detail || "操作已记录")); window.addEventListener("travel-study:notice", onNotice); refresh(); const off = appApi.onTaskUpdate?.((task) => { setTasks((current) => [task, ...current.filter((item) => item.id !== task.id)]); if (task.status === "succeeded" && task.kind === "video-analysis") { setVideoId(task.entity_id); appApi.getScenes(task.entity_id).then((rows) => { if (!rows.length) return; const normalized = rows.map((row, index) => ({ ...row, index: index + 1, frameCount: row.keyframes?.length || 3, range: `${Math.floor(row.start_sec / 60).toString().padStart(2, "0")}:${Math.floor(row.start_sec % 60).toString().padStart(2, "0")} – ${Math.floor(row.end_sec / 60).toString().padStart(2, "0")}:${Math.floor(row.end_sec % 60).toString().padStart(2, "0")}`, defaultSelected: Array.from({ length: row.keyframes?.length || 3 }, (_, i) => i) })); setSceneRows(normalized); setSelection(Object.fromEntries(normalized.map((row) => [row.id, row.defaultSelected]))); setActiveScene(normalized[0]?.id); setScreen("selection"); }); } if (task.status === "succeeded" && (task.kind === "clip-pdf" || task.kind === "note-merge")) refresh(); if (task.status === "failed") setNotice(task.error || "任务失败，可在任务中心重试"); }); return () => { window.removeEventListener("travel-study:notice", onNotice); off?.(); }; }, []);
  const timedTransition = (label, target, delay = 900) => { setProcessing(label); window.setTimeout(() => { setProcessing(""); setScreen(target); }, delay); };
  const toggleScene = (sceneId) => { const scene = sceneRows.find((item) => item.id === sceneId); if (!scene) return; setSelection((current) => ({ ...current, [sceneId]: current[sceneId].length === scene.frameCount ? [] : Array.from({ length: scene.frameCount }, (_, index) => index) })); };
  const toggleFrame = (sceneId, frame) => setSelection((current) => ({ ...current, [sceneId]: current[sceneId].includes(frame) ? current[sceneId].filter((item) => item !== frame) : [...current[sceneId], frame].sort((a, b) => a - b) }));
  const startVideo = async (mode) => { if (!isElectron) { void loadSelectionScreen(); timedTransition("正在压缩视频并识别关键场景…", "selection", 1200); return; } try { const result = mode === "sample" ? await appApi.useSampleVideo() : await appApi.pickVideo(); if (result?.video) { setVideoId(result.video.id); setNotice("视频已加入任务中心，分析完成后将自动打开场景选择"); setTaskCenterOpen(true); } } catch (error) { setNotice(error.message); } };
  const generate = async () => { if (isElectron && videoId) { await appApi.generateClip({ videoId, selections: selection, settings }); setTaskCenterOpen(true); setNotice("已提交 PDF 生成任务，可继续浏览其他页面"); return; } setProcessing("正在渲染 H5 页面并生成 PDF…"); window.setTimeout(() => { setProcessing(""); setCompleted(true); }, 1100); };
  const activeTasks = tasks.filter((task) => task.status === "running" || task.status === "queued").length;
  return <AppShell active={screen} onNavigate={setScreen} projectName={projectName}><Suspense fallback={processing ? null : <ProcessingOverlay label="正在打开工作区…" />}>
    {screen === "workbench" && <WorkbenchScreen processing={Boolean(processing)} onPrefetch={loadSelectionScreen} onStart={startVideo} />}
    {screen === "selection" && <SelectionScreen scenes={sceneRows} selection={selection} activeScene={activeScene} setActiveScene={setActiveScene} onToggleScene={toggleScene} onToggleFrame={toggleFrame} view={view} setView={setView} onNext={() => timedTransition("正在转写所选场景语音…", "transcript")} />}
    {screen === "transcript" && <TranscriptScreen scenes={sceneRows} selection={selection} transcripts={transcripts} setTranscripts={setTranscripts} onBack={() => setScreen("selection")} onNext={() => setScreen("template")} />}
    {screen === "template" && <TemplateScreen settings={settings} setSettings={setSettings} onBack={() => setScreen("transcript")} onGenerate={generate} standalone={false} />}
    {screen === "library" && <LibraryScreen clips={clipData} selectedClips={selectedClips} setSelectedClips={setSelectedClips} onMerge={() => setMergeOpen(true)} onOpen={(id) => appApi.openArtifact("clip", id)} />}
    {screen === "notes" && <NotesScreen notes={notes} onOpen={(id) => appApi.openArtifact("note", id)} />}
  </Suspense>{processing && <ProcessingOverlay label={processing} />}{completed && <CompletionModal onClose={() => setCompleted(false)} onLibrary={() => { setCompleted(false); setScreen("library"); }} />}{mergeOpen && <MergeModal selectedClips={selectedClips} clipData={clipData} onClose={() => setMergeOpen(false)} onComplete={async (cover) => { setMergeOpen(false); if (isElectron) { await appApi.mergeNotes({ clipIds: selectedClips, cover }); setSelectedClips([]); setTaskCenterOpen(true); setNotice("已提交游学笔记合并任务"); } else timedTransition("正在合并片段并生成封面…", "notes", 1000); }} />}{isElectron && <div className="task-center-wrap"><button className="task-center-button" onClick={() => setTaskCenterOpen((open) => !open)}>任务中心{activeTasks ? ` · ${activeTasks}` : ""}</button>{taskCenterOpen && <div className="task-center-panel"><div className="task-center-head"><b>任务中心</b><button className="icon-button" onClick={() => setTaskCenterOpen(false)}>×</button></div>{tasks.length === 0 && <p className="task-empty">暂无任务</p>}{tasks.slice(0, 8).map((task) => <div className="task-row" key={task.id}><div><b>{task.kind === "video-analysis" ? "视频分析" : task.kind === "clip-pdf" ? "生成游学片段" : "合并游学笔记"}</b><small>{task.stage} · {Math.round((task.progress || 0) * 100)}%</small></div><span className={`task-status ${task.status}`}>{task.status === "succeeded" ? "完成" : task.status === "failed" ? "失败" : task.status === "running" ? "进行中" : "排队"}</span>{task.status === "failed" && <button className="text-button" onClick={() => appApi.retryTask(task.id, "checkpoint")}>重试</button>}</div>)}</div>}</div>}{notice && <button className="app-notice" onClick={() => setNotice("")}>{notice}</button>}</AppShell>;
}
